### ISSUE TITLE
Membership Module Enhancements

### ISSUE THREAD

**Issue by ralampay** [cloudband-solutions/microfinancerails#1]
* Automatically tag beneficiary as primary if only one
* Validation for first name, last name and middle name should be unique in combination
* Place signature beside profile picture
* Membership edit validation. When a member is added or edited, change can be approved or rejected for further editing.

**Comment by kathleenlogmao** [comment]
Place signature beside profile picture - OK

**Comment by ralampay** [comment]
Ok thanks :) Please commit, push and check other points and see what else you can com

**Comment by ralampay** [comment]
Validation for first name, last name and middle name should be unique in combination - OK

**Comment by kathleenlogmao** [comment]
Automatically tag beneficiary as primary if only one - OK

**Comment by ralampay** [comment]
Membership edit validation. When a member is added or edited, change can be approved or rejected for further editing. - OK
